### ISSUE TITLE
Q: Transforming Spritesheets - how are STUNS handled?

### ISSUE THREAD

**Issue by LeflairKunstler** [BeatAroundTheBuscher/ROSIGMA#11]
Question to investigate later: 
How to set up the spritesheet / code for STUNS? Where there is a "corpse" rather than transformation? Or does transformation trigger on stun as well?

The transformation (zombie) I´ve found doesn´t include a stun corpse.

**Comment by BeatAroundTheBuscher** [comment]
What do you want to achieve?

**Comment by LeflairKunstler** [comment]
Just wondering how stun is handled with transforming sprite sheets (That don´t have a normal "unit laying down zzzZZZ" animation.
Guess they pull from the floorOB of the corpse? Just wondering if the animation creates a weird look.

**Comment by BeatAroundTheBuscher** [comment]
Yeah, stunned units pull the floorob of the corpse. That zzzZ is an overlay. There is some flag so you can disable it too.
