### ISSUE TITLE
Modding News: UnitSprite Studio Updated

### ISSUE THREAD

**Issue by LeflairKunstler** [BeatAroundTheBuscher/ROSIGMA#15]
Updated to support Snakeman drawing routine 6.
Updated with new Recolor Tool (Buscher, read a lot like your script idea, but with a visual UI).
Updated to support Single Frame FloorOB sprites + recoloring.

Note: It already supports the Sectopod/Reaper/SENTINEL drawing routine.
It does not support the BEHEMOTH drawing routine.

**Comment by BeatAroundTheBuscher** [comment]
Doesn't run on Linux (yet).
Also there is my [2x2 merger](https://openxcom.org/forum/index.php/topic,9548.0.html) for being able to edit other drawing routines
