### ISSUE TITLE
Reminder: Implement Nurgle and Slaanesh infection "plague" code + Medic cure/purify

### ISSUE THREAD

**Issue by LeflairKunstler** [BeatAroundTheBuscher/ROSIGMA#16]
Buschers script.

Relevant units to have infector ability:
Nurgle:
Plaguebearer (exists, implement script for its spit attack+sword?)
Nurgle Blighted  (Exists, give some sort of nurgle grenade launcher, handgrenade or missile for the nurgle launcher)
Replace Nurgle Sisters "seduce" attack with an infection attack instead? STD alert. 
Some sort of Plague Marine special unit or weapon? (There´s an official one with this job)

Slaanesh:
Daemonette variant? Basic daemonette probably should still do its insta-transform thing, but could be given a ranged or AoE ability that infects (turns into more Zombie-Daemonettes on a timer).
Modify "Seduce" Ability to turn people into Traitors/Zombies (I think currently it only puts people to sleep?).
Fiendgor/Bullgor? Claw attack
Some sort of grenade, gun or missile type.

Cure/Purify ability on Medic-units (Their medikits):
-Apotechary
-Medicae
-Hospitaller
-Guard Medic
-Arbites Medic

Buscher: Add your ideas to this thread so we can track it.

**Comment by LeflairKunstler** [comment]
I´ve added the Nurgle Plague Knife and Balesword as enemy weapons + research.
These are suitable for hooking up as research requirements for more advanced purification/purge/cure tech (like medikits).

Once we add more nurgle plague related weapons we can do the same there.

Perhaps Celatid/Plaguebearer research should also be a requirement for some tech in this. Help negate those powerful blight rounds/rockets.

**Comment by BeatAroundTheBuscher** [comment]
This will require an OXCE update.
