### ISSUE TITLE
Reminder: Implementing Dodge Script

### ISSUE THREAD

**Issue by LeflairKunstler** [BeatAroundTheBuscher/ROSIGMA#17]
Buschers Dodge script that visually shifts unit sprite back and forth
Adds a % chance for attacks directed against them to miss.

Use case: Daemons and Super Skilled Dodgy units like Assassins.
High, mid, low dodge chance. 
High = 50-66%
Mid: 25-50%
Low: 10-25%
Very Low: 5%

Or some such. 
Maybe have say 5 different versions of the script that matches these chances to dodge which can then be applied to various units?

Enemy Units:
Assassin type, Slaanesh/Tzeentch - Not sure about Khorne or Nurgle. Might not fit their "style". (High Dodge Chance)
Daemonettes (High dodge chance)
Slaanesh Daemon Princess.
Slaanesh Seraphim and Celestian.
Slaanesh Chosen Assassin
Fiendgor/Slaangors (very small dodge chance)

Friendly Units:
Imperial Assassins, Callidus (very high), other types: Somewhat lower. 
Death Cult Assassin and Adeptas Assassin: low-to-mid
Repentia: Rather low, 5-10%?
Assault Type units: Seraphim and Assault Marines, 5-15%. Just a little something to represent their high mobility/speed/jet pack-strafing.

Other units? 

Buscher: Add your thoughts here.

**Comment by BeatAroundTheBuscher** [comment]
Should explosives or any other AoE be dodge-able?
Also we don't need 5 scripts as we can use the percentage as a parameter/tag.
In my opinion high dodge chance should only be available to very squishy troops which can even be hurt by autoguns.

**Comment by BeatAroundTheBuscher** [comment]
An example is implemented for the STR_ADEPTAS_CALLIDUS_SUIT
