### ISSUE TITLE
Memory Note: Check how Sentinels deploy from Adeptas transports

### ISSUE THREAD

**Issue by LeflairKunstler** [BeatAroundTheBuscher/ROSIGMA#18]
Do sentinels even work with the Black Star?

**Comment by BeatAroundTheBuscher** [comment]
Keep the Space Hulk mission in mind. The 40k devs will probably change the map. If they don't we should consider doing it.

**Comment by LeflairKunstler** [comment]
Sentinels deploy fine from Adeptas Blackstar and the new drop pod.

Will see about that space hulk mission, I noticed the drop pods bloody wreck the terrain of the guard fort maps.
