### ISSUE TITLE
High priority: Create Drop-pod option for Adeptas

### ISSUE THREAD

**Issue by LeflairKunstler** [BeatAroundTheBuscher/ROSIGMA#19]
I have recolored the map pck into a black set of drop pods. Unsure if any other map related file needs updating, or how to tie it all up in a nice little bow. It doesn´t appear to be using the same spritesheet coding as normal assets.

Code wise:
STR_DROP and STR_SKYRANGER appear to be drop pods in  the 40k ruleset, but what determines which color version they use?
A weird thing with these two entries:
Both have similar stats.
But one uses sprite "23" and the other "28", which in extrasprites INTICON.PCK refers to the... same sprite?
      23: Resources/Droppod/Droppod_minimised.gif
      28: Resources/Droppod/Droppod_minimised.gif
There´s no other sprite reference in their code, so its all handled through the map files. 

Stat differences:
damageMax: 35
damageMax: 200

STR_DROP
    weapons: 0
    costBuy: 50000
    costRent: 5000
    soldiers: 4
    vehicles: 1
    refuelRate: 50
    transferTime: 10

STR_SKYRANGER drop pod:
    weapons: 0
    soldiers: 12
    vehicles: 1
    refuelRate: 50
    transferTime: 10

So STR_DROP = Singular drop pod.
Can´t find how the "drop pods" are bought or manufactured.

Sisters recolor:
Some sort of black+red/white combo.

I have uploaded a quick black recolor in a new TERRAIN folder. .PCK and .TAB files. Not sure how to hook them up with code for a "new" drop pod however.

Have uploaded some base UI mini drop pods sprites that need hooking up in extraSprites + the drop craft code in Adeptas.

I´ve added STR_DROPPODS_ADEPTAS to the Adeptas rulfile craft section. Pretty sure it doesn´t link to the correct sprites right now, will need a look at.

**Comment by BeatAroundTheBuscher** [comment]
Commited
