### ISSUE TITLE
Pre-Release Testing (1.01): VFX New Nurgle 40mm Grenades

### ISSUE THREAD

**Issue by LeflairKunstler** [BeatAroundTheBuscher/ROSIGMA#21]
Added the Light Kombibolter with underslung grenade launcher shooting 40mm Blight and "Acid Rust" grenades. I
ve hooked them up to existing small explosion graphics, in the X1 and SMOKE pck extrasprites.
Possible those don´t work as intended when it´s an AoE weapon with damageType 8 (ACID). At least, according to the ruleset reference the damageType determines which .pck the explosionAnimation pulls from. Maybe.

Give it a try and see if it looks OK.

**Comment by BeatAroundTheBuscher** [comment]
IMPACT of the bless abilities also uses an "explosion" animation. It's index 96 of X1.PCK
```
  - type: STR_GUARD_OFFICER_BLESS
...
    hitAnimation: {mod: 40k, index: 96}
```

**Comment by LeflairKunstler** [comment]
Looks like its working fine.
