### ISSUE TITLE
Low Priority: New Idea, Berzerker Pull Script

### ISSUE THREAD

**Issue by LeflairKunstler** [BeatAroundTheBuscher/ROSIGMA#26]
I remembered a fun little mechanic from 2012 XCOM, where berserkers (mutons) would take a couple tiles steps towards any shooter that hit them.

Is this possible to pull off in openxcom? I.e, on the players turn, if they hit a berzerker (or whatever unit has the script), the berzerker will move 1-3 tiles  towards the shooter (it will not attack however, even if bumping up against the shooter).

The counter to this is to use the mechanic to "juggle" a berzerker between two shooters.

An idea if we want to make some enemy melee units a little more spicy.

**Comment by BeatAroundTheBuscher** [comment]
There is no setpos or the like for scripting. I don't think that's possible without changing the engine.
