### ISSUE TITLE
Armor Damage Script - Grav Weapons

### ISSUE THREAD

**Issue by LeflairKunstler** [BeatAroundTheBuscher/ROSIGMA#27]
Remember that script that does damage to all sides of a units armor?

Was wondering if this can be developed further, where a weapons damage scales with the targets armor value (how this is determined: the highest value or the average of all armor sides? - or simply the armor from the angle you hit the target if that's easier).

So a gravgun or grenade with this script would do more damage the more armor the target has X some modifier. Multiplicative is probably what would make it interesting, while a flat power+Armor Value would just work the same as armorEffectiveness. 

Like Armorvalue + 50% = hits a 100 AV target, does 150 power damage. Hit a 30 AV target, does 45 power hit, or 15 damage to health after armor. Can be combined with damage to armor of course.
This would make this weapon type ineffective vs cultists and such, but very good vs power armor and especially terminators/dreads.

Light Grav modifier: AV + 25% (Gravpistol)
Medium Grav modifier: AV + 50% (Gravgun)
Heavy Grav modifier: AV + 100% (Gravcannon)

**Comment by LeflairKunstler** [comment]
use the damageUnit hook.
(0-armor value)*GravModifier (1.25, 1.5, 2.0)

**Comment by BeatAroundTheBuscher** [comment]
do-able
