### ISSUE TITLE
Content Summary

### ISSUE THREAD

**Issue by LeflairKunstler** [BeatAroundTheBuscher/ROSIGMA#3]
Buscher, I´ve uploaded a summary of content changes, it´s the file "ROSIGMA notes" (I´ve uploaded a .txt if you can´t open the .rtf) in the main folder. 

I´ve added lines where you can add your content additions / balance changes. Meant for the mod.io and forum thread summaries.

**Comment by BeatAroundTheBuscher** [comment]
added my notes to the .txt file
