### ISSUE TITLE
UFOPEDIA bugcheck

### ISSUE THREAD

**Issue by LeflairKunstler** [BeatAroundTheBuscher/ROSIGMA#33]
Does referencing image_id 1ML.SPK, 1HB.SPK etc from the base mod, in the ufopedia code, cause crashes?
If so, does {mod: 40k, index: 1ML.SPK} work?
Or do we have to copy the related images into our codex folder and create .spk entries.

**Comment by BeatAroundTheBuscher** [comment]
This doesn't cause any issues. You can use the ufopaedia pictures from the base mod without copying them
