### ISSUE TITLE
Forum Post Draft

### ISSUE THREAD

**Issue by LeflairKunstler** [BeatAroundTheBuscher/ROSIGMA#5]
I´ve expanded upon the mod.io content .txt (see attached file, if this works) with a brief introduction for the forum post, and inserted comments in brackets [Slaanesh Weapons summary] where I think we can insert some pictures.
I´ve already finished a bunch, but I´ve noted a couple of imperial guard related inventory pictures that we could use.
Now, to make inventory art readable in the forum post I´ve blown mine up by 75% or so, and given them a neutral/contrast color background (nothing too stingy or the unit blends into), for the imperial guard we need:
Jump Troops
Mordian guard
New Sentinels
Vindicare
New Guard Weapons (my compilations are basically 200 pixels tall, and then extended out width wise to 1000-1600 pixels depending on number of weapons, with the weapons lined up + ammo beneath them).

I´ve included the imgur links for the compilations I´ve finished. If compression butchers them too much we can use my KWK comic server for hosting.

When we got that in place, we just need some ingame screenshots like we discussed yesterday.

[Forumpostdraft.txt](https://github.com/BeatAroundTheBuscher/ROSIGMA/files/6336903/Forumpostdraft.txt)

**Comment by LeflairKunstler** [comment]
New draft version with image links and some structure tweaks:
[Forumpostdraft.txt](https://github.com/BeatAroundTheBuscher/ROSIGMA/files/6341221/Forumpostdraft.txt)

**Comment by BeatAroundTheBuscher** [comment]
Was posted.
