### ISSUE TITLE
Problem: Research unlocks Unit (Soldier) Buy Function [STR_ADEPTAS]

### ISSUE THREAD

**Issue by LeflairKunstler** [BeatAroundTheBuscher/ROSIGMA#9]
Writing down some notes on the problem and possible workarounds after giving the issue some thought.

The basic idea is that a certain technology research shall unlock the ability to recruit a type of unit. Knowing how this works will be useful not only for STR_ADEPTAS, but additional imperial guard units etc.

Normally, this function:
**Requires |** _List of topics  (string IDs) that must be researched to unlock this soldier type. If  none are specified, this soldier type is unlocked from the start.
Should allow a tech to restrict the recruitment of this soldier type. In the case of the STR_ADEPTAS + requirement STR_ADEPTAS_SOB_MOBILIZATION does not work as expected.

FIrst problem solution idea: STR_ADEPTAS is shared with both unit, category and a research (Faction) topic. The engine is confused by this.
Proposed Solution: Rename STR_ADEPTAS (the unit) to STR_ADEPTAS_SOLDIER
Outcome: No difference, solution does not work.

Second problem solution idea: STR_ADEPTAS_SOB_MOBILIZATION needs to "Unlock" a "requirement", I do not know why it works this way, but for several weapon restrictions, like - STR_HEAVY_WEAPONS_RESEARCH_REQ, this is how the tech needs to be setup to work as a requirement. My guess is that the "Research topic" confuses the engine, in that the topic itself is "available" for research at game start, so the engine cannot differentiate from a unlocked research topic and a researched research topic. I.e, the unlock is required.
Proposed Solution: Add a unlock called "STR_ADEPTAS_RECRUITMENT_REQ" to the STR_ADEPTAS_SOB_MOBILIZATION research topic, and as a requirement to STR_ADEPTAS (the unit).
Outcome: Implemented in github, test: No change in outcome

Third problem solution idea:
requiresBuyBaseFunc couldbe a workaround, where the tech unlocks a specific building, that then unlocks the recruitment of STR_ADEPTAS. This might require a new building type, or one that is already unlocked early (the adamantium forge for example, fluff explanation: Power Armor manufacturing capability).
Proposed Solution: Make the Adamantium forge Tech base function a requirement to recruit STR_ADEPTAS.
Outcome: Tested, it works.

**Comment by BeatAroundTheBuscher** [comment]
Can this be closed?

**Comment by LeflairKunstler** [comment]
Yes!
